#!/usr/bin/env python
"""Create a normal multi-page PDF for retrieval testing (non-legal content)."""

from fpdf import FPDF
import os

OUTPUT = "E:/trae/cede/mcu-rag-qa-v2/data/test_normal_pdf.pdf"
os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)

pdf = FPDF()
font_path = "C:/Windows/Fonts/msyh.ttc"
if os.path.exists(font_path):
    pdf.add_font("CJK", "", font_path, uni=True)
    pdf.set_font("CJK", size=12)
else:
    pdf.set_font("Helvetica", size=12)

pages = [
    ["Python Programming Guide", "",
     "Python is a high-level, interpreted programming language created by Guido van Rossum in 1991.",
     "It emphasizes code readability with its notable use of significant indentation.",
     "Python is dynamically-typed and garbage-collected. It supports multiple programming paradigms.",
     "Python is often described as a batteries included language due to its comprehensive standard library.",
     "The language has a large and active community, with millions of developers worldwide.",
     "Python is widely used in web development, data science, artificial intelligence, and automation.",
     "",
     "Key features of Python include:",
     "  - Easy-to-read syntax with English-like keywords",
     "  - Dynamic typing and automatic memory management",
     "  - Comprehensive standard library with built-in modules",
     "  - Cross-platform compatibility (Windows, macOS, Linux)",
     "  - Extensive third-party package ecosystem (PyPI)",
     "  - Support for multiple programming paradigms",
     "  - Strong community support and documentation"],
    ["Data Types and Variables", "",
     "Python has several built-in data types:",
     "",
     "Numeric Types: int, float, complex",
     "  int: 42, -7, 0",
     "  float: 3.14, -0.5, 1.0e10",
     "",
     "Sequence Types: list, tuple, range",
     "  list: [1, 2, 3], ['a', 'b', 'c']",
     "  tuple: (1, 2, 3), ('a', 'b')",
     "",
     "Text Type: str",
     "  'hello', \"world\", '''multi-line string'''",
     "",
     "Mapping Type: dict",
     "  {'name': 'Alice', 'age': 30}",
     "",
     "Set Types: set, frozenset",
     "  {1, 2, 3}, frozenset([1, 2])",
     "",
     "Boolean Type: bool",
     "  True, False",
     "",
     "Variables do not need explicit declaration. A variable is created when you assign a value."],
    ["Control Flow Statements", "",
     "Python supports standard control flow statements:",
     "",
     "if Statement:",
     "  x = 10",
     "  if x > 0: print('Positive')",
     "  elif x == 0: print('Zero')",
     "  else: print('Negative')",
     "",
     "for Loop:",
     "  for i in range(5): print(i)",
     "  for key, value in my_dict.items(): print(key, value)",
     "",
     "while Loop:",
     "  count = 0",
     "  while count < 5: print(count); count += 1",
     "",
     "List Comprehensions:",
     "  squares = [x**2 for x in range(10)]",
     "  evens = [x for x in range(20) if x % 2 == 0]",
     "",
     "The range function generates sequences of numbers.",
     "The enumerate function adds a counter to an iterable.",
     "The zip function combines multiple iterables element-wise."],
    ["Functions and Modules", "",
     "Functions are defined using the def keyword:",
     "  def greet(name): return f'Hello, {name}!'",
     "  def add(a, b): return a + b",
     "",
     "Python supports default arguments:",
     "  def power(base, exp=2): return base ** exp",
     "",
     "Keyword arguments:",
     "  result = power(exp=3, base=2)",
     "",
     "Lambda functions (anonymous):",
     "  square = lambda x: x**2",
     "",
     "Modules are files containing Python definitions:",
     "  import math",
     "  from datetime import datetime",
     "  import json as json_module",
     "",
     "Packages are collections of modules:",
     "  from mypackage import module1",
     "  from mypackage.module2 import function",
     "",
     "The standard library includes: os, sys, json, re, math, datetime, collections, itertools"],
    ["File I/O and Exception Handling", "",
     "File Operations:",
     "  with open('file.txt', 'r') as f: content = f.read()",
     "  with open('file.txt', 'w') as f: f.write('Hello, World!')",
     "  with open('file.txt', 'r') as f:",
     "      for line in f: print(line.strip())",
     "",
     "Exception Handling:",
     "  try:",
     "      result = 10 / 0",
     "  except ZeroDivisionError:",
     "      print('Cannot divide by zero!')",
     "  except ValueError as e:",
     "      print(f'Value error: {e}')",
     "  else: print('No exception occurred')",
     "  finally: print('This always runs')",
     "",
     "Raising exceptions:",
     "  def validate_age(age):",
     "      if age < 0: raise ValueError('Age cannot be negative')",
     "      return age",
     "",
     "Common exception types: TypeError, ValueError, KeyError, IndexError, FileNotFoundError, IOError"],
    ["Object-Oriented Programming", "",
     "Python supports OOP with classes:",
     "  class Animal:",
     "      def __init__(self, name): self.name = name",
     "      def speak(self): raise NotImplementedError",
     "",
     "  class Dog(Animal):",
     "      def speak(self): return f'{self.name} says Woof!'",
     "",
     "Key OOP concepts:",
     "  Inheritance: class Child(Parent)",
     "  Encapsulation: _protected, __private (name mangling)",
     "  Polymorphism: duck typing",
     "  Multiple inheritance: class C(A, B)",
     "",
     "Special methods (dunder methods):",
     "  __init__, __str__, __repr__, __len__",
     "  __getitem__, __setitem__, __iter__",
     "  __enter__, __exit__ (context managers)",
     "",
     "Properties:",
     "  class Circle:",
     "      @property",
     "      def area(self): return 3.14 * self.radius ** 2",
     "",
     "Static methods use @staticmethod decorator.",
     "Class methods use @classmethod decorator."],
    ["Working with Data", "",
     "Python excels at data manipulation:",
     "",
     "JSON Handling:",
     "  import json",
     "  data = {'name': 'Alice', 'scores': [90, 85, 92]}",
     "  json_str = json.dumps(data, indent=2)",
     "  parsed = json.loads(json_str)",
     "",
     "Regular Expressions:",
     "  import re",
     "  pattern = r'\d+'",
     "  matches = re.findall(pattern, 'abc123def456')",
     "",
     "Date and Time:",
     "  from datetime import datetime, timedelta",
     "  now = datetime.now()",
     "  future = now + timedelta(days=7)",
     "  formatted = now.strftime('%Y-%m-%d %H:%M:%S')",
     "",
     "Collections module provides specialized containers:",
     "  defaultdict, Counter, deque, OrderedDict",
     "The itertools module provides iterator functions:",
     "  chain, cycle, permutations, combinations"],
]

for i, page_lines in enumerate(pages):
    pdf.add_page()
    for line in page_lines:
        pdf.cell(0, 8, line, new_x="LMARGIN", new_y="NEXT")

pdf.output(OUTPUT)
print(f"Created: {OUTPUT}")

from pypdf import PdfReader
r = PdfReader(OUTPUT)
print(f"Pages: {len(r.pages)}")
total = sum(len(p.extract_text() or "") for p in r.pages)
print(f"Total chars: {total}")
